pipeline {
    agent any

    stages {
        stage('Build Backend Image') {
            steps {
                sh 'docker build -t backend-app CC_Lab-6/backend'
            }
        }

        stage('Deploy Backends') {
            steps {
                sh '''
                docker rm -f backend1 backend2 || true
                docker run -d --name backend1 backend-app
                docker run -d --name backend2 backend-app
                '''
            }
        }

        stage('Deploy NGINX') {
            steps {
                sh '''
                docker rm -f nginx-lb || true
                docker run -d                   --name nginx-lb                   -p 80:80                   -v $(pwd)/nginx/nginx.conf:/etc/nginx/nginx.conf:ro                   nginx
                '''
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed'
        }
    }
}
